### ISSUE TITLE
Writing with archival format always append to existing files

### ISSUE THREAD

**Issue by heavelock** [iris-edu/dataselect#7]
Hi!
Currently, when using a dataselect with for example that command:
```
$ ~/tools/dataselect/dataselect -v -sum -ts 2019,182,0,0,0 -te 2019,182,23,59,59.99999 -Pr -SDS /mnt/D4To/temp/tempsds /datadir/SI.SI30.00.CHE_2019070?_??0000.miniseed
```
If I run it multiple times, dataselect will append data to existing files. 
Is there a possibility of defining what should be done in case of existing file other than executing dataselect with `-o` parameter for each of the requested output files?

**Comment by chad-iris** [comment]
> Is there a possibility of defining what should be done in case of existing file other than executing dataselect with -o parameter for each of the requested output files?

No there is no such control.  The archive option, or any of it's presets such as -SDS, will always append to existing files.  You can either remove the files in the archive prior to running dataselect or write to a separate, temporary location and then copy the files back to the archive replacing them.
