### ISSUE TITLE
Error "making" the program on macOS: xcrun: error: invalid active developer path

### ISSUE THREAD

**Issue by tbartholomaus** [iris-edu/dataselect#9]
Hi Chad et al.,
I'm trying to set up dataselect on my mac (MacOS 10.15.7).  I've git cloned the dataselect directory into /usr/local/bin/ and then typed "make" and I'm getting an error.
```
(base20) [TCB-MBP] dataselect $ make
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
(base20) [TCB-MBP] dataselect $ ls
ChangeLog LICENSE   Makefile  README.md doc       libmseed  src
(base20) [TCB-MBP] dataselect $
```

Can you be a little more detailed in the README.md or in the doc directory, about how best to install and get dataselect up and running on different systems?

Thanks! Tim

**Comment by chad-iris** [comment]
Hi @tbartholomaus,

That error looks like a system problem and nothing to do with dataselect itself.  I've added some details to the README, but really this comes down to having a working build environment (C compiler and make program) on your system.

I ran a Google search for "xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun"

and this is the top hit:
https://ma.ttias.be/mac-os-xcrun-error-invalid-active-developer-path-missing-xcrun/

**Comment by tbartholomaus** [comment]
Sorry for what turned out to be a trivial "issue" @chad-iris, I got spooked when I saw "build from source" and I got a first error. And I thought I already had Xcode installed.  Anyway, feel free to adopt or reject my suggested pull request.
Thanks again.

**Comment by chad-iris** [comment]
no worries, thanks for the contribution.
